#!/usr/bin/env python3
"""
Migrate all data from one Zilliz Cloud instance to another.

Usage:
    Set environment variables for source and destination, then run:

    SOURCE_URI=https://source.zilliz.com \
    SOURCE_API_KEY=your_source_key \
    DEST_URI=https://dest.zilliz.com \
    DEST_API_KEY=your_dest_key \
    python scripts/migrate_zilliz.py

Optional env vars:
    SOURCE_COLLECTION   (default: colleges)
    DEST_COLLECTION     (default: same as SOURCE_COLLECTION)
    BATCH_SIZE          (default: 1000)
    DROP_IF_EXISTS      set to "true" to drop destination collection first
"""

import os
import sys
import time

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

from pymilvus import (
    connections,
    Collection,
    FieldSchema,
    CollectionSchema,
    DataType,
    Function,
    FunctionType,
    utility,
)

# ── Config ────────────────────────────────────────────────────────────────────

SOURCE_URI = os.environ["SOURCE_URI"]
SOURCE_API_KEY = os.environ["SOURCE_API_KEY"]
SOURCE_COLLECTION = os.getenv("SOURCE_COLLECTION", "colleges")

DEST_URI = os.environ["DEST_URI"]
DEST_API_KEY = os.environ["DEST_API_KEY"]
DEST_COLLECTION = os.getenv("DEST_COLLECTION", SOURCE_COLLECTION)

BATCH_SIZE = int(os.getenv("BATCH_SIZE", "200"))
DROP_IF_EXISTS = os.getenv("DROP_IF_EXISTS", "false").lower() == "true"

VECTOR_DIM = 1536

# All scalar + vector fields to export (must match the collection schema).
# content_sparse is auto-generated by BM25 function — never fetched or inserted directly.
OUTPUT_FIELDS = [
    "id",
    "college_name",
    "url",
    "url_canonical",
    "title",
    "content",
    "embedding",
    "page_type",
    "crawled_at",
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def connect(alias: str, uri: str, api_key: str) -> None:
    connections.connect(alias=alias, uri=uri, token=api_key)
    print(f"✓ Connected [{alias}] → {uri}")


def get_schema() -> CollectionSchema:
    from college_ai.scraping.config import MAX_TITLE_LENGTH, MAX_CONTENT_LENGTH

    fields = [
        FieldSchema("id", DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
        FieldSchema("college_name", DataType.VARCHAR, max_length=256),
        FieldSchema("url", DataType.VARCHAR, max_length=2048),
        FieldSchema("url_canonical", DataType.VARCHAR, max_length=512),
        FieldSchema("title", DataType.VARCHAR, max_length=MAX_TITLE_LENGTH),
        FieldSchema(
            "content", DataType.VARCHAR, max_length=MAX_CONTENT_LENGTH,
            enable_analyzer=True, enable_match=True,
            analyzer_params={"type": "english"},
        ),
        FieldSchema("content_sparse", DataType.SPARSE_FLOAT_VECTOR),
        FieldSchema("embedding", DataType.FLOAT_VECTOR, dim=VECTOR_DIM),
        FieldSchema("page_type", DataType.VARCHAR, max_length=64),
        FieldSchema("crawled_at", DataType.VARCHAR, max_length=32),
    ]
    schema = CollectionSchema(fields, description="College pages with hybrid search")
    schema.add_function(Function(
        name="bm25",
        input_field_names=["content"],
        output_field_names=["content_sparse"],
        function_type=FunctionType.BM25,
    ))
    return schema


def ensure_dest_collection(name: str) -> Collection:
    if DROP_IF_EXISTS and utility.has_collection(name, using="dest"):
        print(f"  Dropping existing destination collection '{name}'...")
        utility.drop_collection(name, using="dest")

    if not utility.has_collection(name, using="dest"):
        print(f"  Creating collection '{name}' on destination...")
        col = Collection(name, schema=get_schema(), using="dest")
        col.create_index("embedding", {"index_type": "AUTOINDEX", "metric_type": "COSINE"})
        col.create_index("content_sparse", {"index_type": "SPARSE_INVERTED_INDEX", "metric_type": "BM25"})
        col.create_index("college_name", {"index_type": "INVERTED"}, index_name="college_name_idx")
        col.create_index("url_canonical", {"index_type": "INVERTED"}, index_name="url_canonical_idx")
        col.create_index("page_type", {"index_type": "INVERTED"}, index_name="page_type_idx")
        print(f"  ✓ Collection + indexes created")
    else:
        col = Collection(name, using="dest")
        print(f"  ✓ Using existing destination collection '{name}'")

    col.load()
    return col


def count_source(col: Collection) -> int:
    col.flush()
    return col.num_entities


# ── Main ──────────────────────────────────────────────────────────────────────

def migrate() -> None:
    print("\n=== Zilliz Cloud Migration ===")
    print(f"  Source:      {SOURCE_URI}  [{SOURCE_COLLECTION}]")
    print(f"  Destination: {DEST_URI}  [{DEST_COLLECTION}]")
    print(f"  Batch size:  {BATCH_SIZE}")
    print()

    # Connect both instances
    connect("src", SOURCE_URI, SOURCE_API_KEY)
    connect("dest", DEST_URI, DEST_API_KEY)

    # Open source collection
    if not utility.has_collection(SOURCE_COLLECTION, using="src"):
        print(f"ERROR: Source collection '{SOURCE_COLLECTION}' does not exist.")
        sys.exit(1)

    src_col = Collection(SOURCE_COLLECTION, using="src")
    src_col.load()

    total = count_source(src_col)
    print(f"  Source record count: {total:,}")

    if total == 0:
        print("  Nothing to migrate.")
        return

    # Prepare destination collection
    dst_col = ensure_dest_collection(DEST_COLLECTION)

    # Use query_iterator to avoid the offset+limit <= 16384 restriction
    migrated = 0
    start = time.time()

    print(f"\nMigrating {total:,} records in batches of {BATCH_SIZE}...\n")

    iterator = src_col.query_iterator(
        expr="id != ''",
        output_fields=OUTPUT_FIELDS,
        batch_size=BATCH_SIZE,
    )

    while True:
        results = iterator.next()
        if not results:
            iterator.close()
            break

        dst_col.insert(results)

        migrated += len(results)
        elapsed = time.time() - start
        rate = migrated / elapsed if elapsed > 0 else 0
        pct = migrated / total * 100
        print(f"  {migrated:>7,} / {total:,}  ({pct:.1f}%)  {rate:.0f} rec/s", end="\r")

    print(f"\n\n  ✓ Migrated {migrated:,} records in {time.time() - start:.1f}s")

    # Flush and rebuild index
    print("  Flushing destination collection...")
    dst_col.flush()
    print(f"  ✓ Done. Destination now has {dst_col.num_entities:,} records.")


if __name__ == "__main__":
    migrate()
